added labs and unit tests for accessibility
liv-ac-uk/comp122 pull request #1
Opened 2020-09-16 13:41 UTC by SurgeArrester

2020-09-16 13:43 UTC, patricktotzke requested changes

2020-09-16 13:43 UTC, patricktotzke commented on problems/accessibility/__init__.py
> +def student_not_update_lower():
this needs changing

2020-09-16 13:44 UTC, SurgeArrester commented on problems/accessibility/__init__.py
> +def student_not_update_lower():
no it doesn't!

2020-09-16 14:00 UTC, patricktotzke requested changes

2020-09-16 14:00 UTC, patricktotzke commented on labs/accessibility/Student.java
> +    ? getTotalGrade() {
perhaps comment out the whole thing and ask students to write uncomment and finish it?
The check50_java check should survive a missing method and simply fail that check if they did not do this.

2020-09-29 10:21 UTC, pazz commented
closed in favour of #4

2020-09-29 10:21 UTC, closed without merging