Constructors
liv-ac-uk/comp122 pull request #2
Opened 2020-09-29 08:45 UTC by SurgeArrester

2020-09-29 09:49 UTC, pazz commented
this does not work on labs.cs50.io due to the syntax errror in the readme

![2020-09-29-104927_1392x402_scrot](https://user-images.githubusercontent.com/628455/94543044-78ef2380-0241-11eb-8ae4-df0d4d0639ac.png)

2020-09-29 11:07 UTC, pazz requested changes

2020-09-29 11:07 UTC, pazz commented on problems/accessibility/tests/StudentTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Please don't check in Junit test source files and instead only commit the compiled stuff here!
(You can push to the materials repo on gitlab to share a copy)

2020-09-29 11:07 UTC, pazz commented on labs/constructors/README.md
> +When we create objects we can use the default constructor. This sets each of the variables to their default values (which is normally $'0'$, `false`, or `""`).
math..

2020-10-03 15:04 UTC, patricktotzke commented on problems/accessibility/tests/StudentTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Oh and I just noticed that this whole commit adds the "accessibility" pset. This was probably added to this PR by accident and should go into #4 instead. Otherwise You'll get conflicts when we merge the first of these branches.

2020-11-19 15:49 UTC, merged