Removed loops from lab
liv-ac-uk/comp122 pull request #3
Opened 2020-09-29 08:54 UTC by SurgeArrester

2020-09-29 09:39 UTC, pazz commented on labs/flowControl/README.md
> +{% spoiler "Hint"}
didn't i fix this before already?

2020-09-29 09:51 UTC, pazz commented on labs/flowControl/README.md
> +{% spoiler "Hint"}
This is the reason for lab.cs50.io not working (see also #2 )

2020-10-07 09:12 UTC, patricktotzke commented
This looks good to me. We're missing a problem set to check the submission.
Perhaps this lab (and problem set and with it the slug) should now be called "leapYear"?

2020-10-19 18:33 UTC, patricktotzke commented
I believe we still want to input strings and not ints in the checks..
Also, I could be wrong but wasn't there a separate exercise to compute leap-years using Boolean combinations? If so, perhaps there should be checks for that too.

2020-10-20 07:24 UTC, patricktotzke commented
Math service down?
This is how the lab looks on labs.cs50.io (and github) as of today:

![2020-10-20-082343_499x589_scrot](https://user-images.githubusercontent.com/58143278/96553822-a01f9a80-12ad-11eb-9a5d-8a4d75997ecc.png)

2020-10-20 07:27 UTC, patricktotzke approved these changes

2020-10-20 07:32 UTC, patricktotzke requested changes

2020-10-20 07:32 UTC, patricktotzke commented on labs/flowControl/README.md
> +In our Gregorian calendar, a leap year is a year that is divisible by ![equation](https://latex.codecogs.com/gif.latex?4), except if it is also divisible by ![equation](https://latex.codecogs.com/gif
![2020-10-20-082916_887x482_scrot](https://user-images.githubusercontent.com/58143278/96554417-6b601300-12ae-11eb-8898-a5d22aca2b12.png)

It looks like their certificates are too old for my browser to accept. This isn't really a durable setup I think..

2020-10-20 07:32 UTC, patricktotzke commented on labs/flowControl/README.md
>  check50 liv-ac-uk/comp122/2021/labs/variables
Check your code using

```
check50 liv-ac-uk/comp122/2021/labs/flowControl
```

Submit via

```
submit50 liv-ac-uk/comp122/2021/labs/flowControl
```

2020-12-03 14:16 UTC, pazz commented
(added as "leapYears" with small mods)

2020-12-03 14:16 UTC, closed without merging