Accessibility
liv-ac-uk/comp122 pull request #4
Opened 2020-09-29 10:21 UTC by SurgeArrester

Updated changes

2020-09-29 11:01 UTC, pazz requested changes
Was the stuff under `labs/objects` supposed to be another lab (in a separate PR)?
In any case, you are missing a `.cs50.yml` file there, so the web-thing doesn't pick it up.

2020-10-07 09:00 UTC, pazz approved these changes

2020-10-07 09:05 UTC, patricktotzke requested changes

2020-10-07 09:05 UTC, patricktotzke commented on labs/accessibility/README.md
> +check_50 TODO FINAL PROGRAM SLUG HERE
We already know the slug:

```
check50 liv-ac-uk/comp122/2021/problems/accessibility
```

and the same slug for submit50.
This needs a problem set in this folder: https://github.com/liv-ac-uk/comp122/tree/abf346186f00644bce2454376161e9aac80347da/problems

which is the last thing missing for this PR I guess

2020-11-19 16:07 UTC, closed without merging